apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "dask.fullname" . }}-master
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: scheduler
spec:
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: scheduler
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        {{- toYaml .Values.scheduler.image.pullSecrets | nindent 8 }}
      containers:
        - name: {{ template "dask.fullname" . }}-scheduler
          image: "dask-pod:0.0.2"
          imagePullPolicy: Never
          command:
          - /bin/sh
          - -c
          - mc alias set myminio http://192.168.1.55:9000 minioadmin minioadmin; echo 3; mc cp myminio/mybucket/thetest.py ./test.py; echo 4; python ./test.py; echo 5; mc cp ./output.txt myminio/mybucket/outputs/joboutput.txt; echo 6; 
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
{{ end }}
