FROM daskdev/dask:2022.1.1-py3.8

COPY requirements-ml-minimal.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt
RUN pip install psycopg2-binary