{{ if .Values.scheduler.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: scheduler
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: scheduler
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: scheduler
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        {{- toYaml .Values.scheduler.image.pullSecrets | nindent 8 }}
      containers:
        - name: {{ template "dask.fullname" . }}-scheduler
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          args:
            - dask-scheduler
            - --port
            - "{{ .Values.scheduler.servicePort }}"
            - --dashboard-address
            - "8787"
            {{- if .Values.scheduler.extraArgs }}
              {{- toYaml .Values.scheduler.extraArgs | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          env:
            {{- toYaml .Values.scheduler.env | nindent 12 }}
    {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.scheduler.serviceAccountName }}
      serviceAccountName: {{ .Values.scheduler.serviceAccountName | quote }}
    {{- end }}
{{ end }}
