apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: connectors
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-seed
          configMap:
            name: postgres-seed
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          volumeMounts:
            - name: postgres-seed
              mountPath: /home/postgres/seed
