# permissions for end users to edit daskjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daskjob-editor-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - daskjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - daskjobs/status
  verbs:
  - get
