# permissions for end users to view daskjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daskjob-viewer-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - daskjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - daskjobs/status
  verbs:
  - get
